### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by majorku5anagi** [Azure/aztfy#105]
Hi, tool is working great in this early stage but I had to wonder if the team is planning to introduce code refactoring? Import is being made in very raw format, plain values are all imported into `main.tf` file which as a result forces you to refactor the code by yourself and manually cut/copy/paste values into `variables.tf`, `terraform.tfvars`, `output.tf` or other `.tf` files that you have to create by yourself. 

Assuming that future development of the tool would introduce import scope on the subscription level, couple of different approaches to refactoring could be offered in the `aztfy` command which will create module/subfolder structure based on the chosen refactoring style.

I assume that this would also need some `Azure CAF` based schema file for the resource naming convention that will be used during the import (prefixes, numbering, etc.), so maybe some `.json` template file could be offered for the download. For example, mentioned `.json` file could contain variable definition for each resource type like the prefix, middle sections, suffix, incremental sections and separators. Maybe in this definition we could also have at disposal some imported variables from the current `AZ Context` like subscription name, resource group name, etc.

**Comment by magodo** [comment]
@majorku5anagi Thank you for the advice! We've indeed internally discussed about the improvement of the output.

In short, currently our focus is to improve the availability of the tool for different kinds of resources within the resource group, as some resources are modeled differently between ARM and terraform, some adhoc handlings are needed to make them importable. Besides, we are planning to improve the mapping from ARM resource id to the terraform resource type, so as to save user's effort.

Back to the output format, it is a challenge for us to identify which attributes are meant to be input variables or outputs as different users have different opinions. Even supporting the implicit dependency between resources are not a trivial work (currently, only explict dependency is available via `depends_on`), as some Azure resource are referencing the "name" of the depending resources, rather than `id`.

Arguably, refactoring the raw `main.tf` to a Terraform idiomatic layout can be done via another separate tool, something like the "code refactoring" feature in the IDE. Therefore, unfortunately we are not planning to make this happen for this tool at this moment.

**Comment by majorku5anagi** [comment]
@magodo Thanks for the reply! Again, I have to say that even at this stage, this project echoed with extremely positive feedback across the community as it is seen as potential main migration tool for organizations that already have their infrastructure built and want to implement cloud-agnostic IaaC with Terraform. Other tools for importing AZ resources into Terraform code like `Terraformer `or `Terracognita` that can be found here on GitHub gave only partial results because of the list of supported resources (and sometimes quality/details of the code itself).

Probably I should have mentioned this in my original post about the code refactoring output, [Terracognita ](https://github.com/cycloidio/terracognita) was actually an inspiration for my original question because it has already built-in refactoring in modules divided per resource type. Sure it's just one refactoring style but it gives you far greater flexibility to work with something like that.

Once more, kudos for the team and the achievement! This tool has enormous potential! 🥇 

P.S. 

When you've mentioned code refactoring feature in IDE, did you have something particular in mind as I would really like to try it out?

**Comment by magodo** [comment]
@majorku5anagi Thank you! There are still a lot of work in progress, tbh :)

For refactoring Terraform code, currently I didn't investigate it too much. So the only solution I can tell is the [official `move` block](https://www.terraform.io/language/modules/develop/refactoring).

**Comment by magodo** [comment]
As is said in another issue, you can use some simple commands to split the generated configuration into multiple files, per resource type: https://github.com/Azure/aztfy/issues/108#issuecomment-1136678592. For some general refactorings, I think it deserves to create a separate tool.

With above, I'm gonna close this issue for now. Please feel free to reopen it you have have further questions.
