### ISSUE TITLE
Automatically detect path to mapping file

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfy#138]
Uses path to mapping file instead of name. Default to looking for default name used in save operation.

**Comment by magodo** [comment]
I think explict is better than implicit. The issue here is that once resource mapping file is used, the resource type auto deduction will stop to work, but just rely on what is specified in the resource mapping. If we implicitly read in a mapping file with a default name in the specified output directory, then the mapping result might be supprized for users, that they expect them to be auto deduced.

**Comment by stemaMSFT** [comment]
We'll get validation from customers to see if we should continue forward with this.
