### ISSUE TITLE
Refactor mapping file

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfy#223]
Refactoring mapping file to consist of JSON objects defined by their azure resourceID. They'd have two properties: `tf_type` and `tf_name`

**Comment by magodo** [comment]
@stemaMSFT So the proposed format is as below:

```
{
  "tf_id": {
    "resource_type": xxx,
    "resource_name": xxx
  }
}
```

While I'd like to change this a bit to something like below:

```
{
  "azure_id": {
    "resource_id": xxx,
    "resource_type": xxx,
    "resource_name": xxx
  }
}
```

`azure_id` is the azure resource id, in upper case (since RP tends to change the casing and azure is actually case insensitive for resource id). `resource_id` is the Terraform resource id (case sensitive). In most case, both are the same regardless the casing. For the other cases, they might be different.

The reason why using the `azure_id` as the object key here rather than the tf id is that there  are resources that have different `azure_id`, but they have the same tf ids. E.g.

- `azurerm_subnet_network_security_group_association` and `azurerm_subnet`
- `azurerm_postgresql_active_directory_administrator` is a singleton child resource of `azurerm_postgresql_server`, but their tf ids are the same

WDYT?

**Comment by stemaMSFT** [comment]
Hey @magodo, I think we're on the same page here :) I was trying to say that I wanted the azure_id to be the outside property, which is exactly what you have (I didn't think of the terraform ID, but I think that's a wonderful addition). Good to know that you have it upper case since I saw from your conversation about the issues with case sensitivity in the ARG API. Complete supportfrom my end!
