### ISSUE TITLE
Generate a list of unmapped resources if some resources were unable to be mapped

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfy#232]
When running aztfy (in both interactive and non-interactive mode), create a JSON file that details all resources that were not able to be mapped. Potential name "undefinedResources.json" with a potential terminal output "Not all resources could be mapped. A list of resources can be found in the 'undefinedResources.json' file." This will provide clarity to both new users to the tool and batch-running script users alike.

**Comment by magodo** [comment]
@stemaMSFT 

The resources that belongs to the specified scope (e.g. a rg), but won't be terrafied might come from different reasons:

1. The resource is not listed by `azlist`: This might be caused due to the `GET` for that resource has special requirements (e.g. needs a $filter query parameter). ARM export template has the same problem. We can only get an error on the `GET` operation, but won't know what resources are in effect
2. The resource is listed, but it has no counter part in TF. This may because:
    1. The resource is not a PUTable resource (e.g. storage account services)
    2. The resource is not supported by the provider yet

Ultimately, what we want to tell in the *undefinedResources.json* are the resources that belong to the scope, *and they are supported by the provider**. However, there is no easy way to identify those. Otherwise, we will bring more confusion to users. WDYT?

**Comment by stemaMSFT** [comment]
Hey @magodo this clarity is tremendously helpful. I think the experience we're thinking of here is basically if a resource would be listed in the UI as a skip, then especially for users running in non-interactive mode we should have some sort of indication for them to know their resource was not part of the import/export process. That's what gave rise to this `undefinedResources.json` idea.

To me, it's not important actually if they're supported by the AzureRM provider or not, just that users don't mistakenly think certain resources have been imported when they haven't been. With that being said, the reason 1 sounds more convoluted and complicated to explain, but I think we can list all resources that fall under reason 2.i. and 2.ii.

Then, in the JSON in comments we can say "go to (docs link) to read about why your resources may have been undefined by the tool." There, we can list these two scenarios in detail. As a whole, I'm on the same page as you that we want to generate clarity, not confusion. Thoughts?

**Comment by magodo** [comment]
@stemaMSFT This file is only for informative purpose, then I think we can make it just a text file (rather than a json): *ignoredResoruces.txt*?

**Comment by stemaMSFT** [comment]
@magodo not a problem with me!
