### ISSUE TITLE
azurerm_network_interface exports do not include private_ip_address when configured  as static

### ISSUE THREAD

**Issue by Klaas-** [Azure/aztfy#33]
Hi,
I was testing aztfy, you're missing the private ip address when creating the tf code for azurerm_network_interface . This is important when the interface is configured as static. 

Greetings
Klaas

**Comment by magodo** [comment]
@Klaas- Thank you for testing this out! The `ip_configuration.n.private_ip_address` in the `azurerm_network_interface` is a `Computed` + `Optional` property, which is a bit special: if users have specified it, it is working as an `Optional` only property, otherwise, it is working as an `Computed` property. This is set to such for supporting both static and dynamic private ip.

The goal of this tool is to import the infra to Terraform and generate the corresponding configuration, which doesn't have diff by a follow-up plan/apply. Therefore, we simply don't generate configuration for all those `O+C` properties (for the sake of maintainability). This only impacts users when one wants to modify the `private_ip_address` to something else, then one can simply add it up.

**Comment by Klaas-** [comment]
Hi @magodo .
I do get what you're saying but you're wrong about it being computed or optional. It's only optional for dynamic address allocation. On static allocation private_ip_address is a required input parameter. See https://github.com/hashicorp/terraform-provider-azurerm/pull/15264 https://github.com/hashicorp/terraform-provider-azurerm/issues/15265

Never the less, you are right if your goal is simply to get a tf configuration that shows now diff to deployed config then your approach is enough, you will however not get code that can be reapplied in case the VM gets deleted/changed, which would be my goal :)

Greetings
Klaas

**Comment by magodo** [comment]
I assume that *you will however not get code that can be reapplied in case the VM gets deleted/changed* means you want to reproduce your infra via the generated cfg after removing everything. If so, then the tool is currently not able to guarantee 100% reproducible. One reason is as above, the `O+C` properties are not generated (there are several reasons not do that, but the main goal here is to generate a valid config). Another reason is that when you are importing some infra with features that are not available in Terraform (but is supported in Azure), then you'll never be able to be able to reproduce it via Terraform anyway.

But one might argue that the tool should allow me to reproduce the infra if it was provisioned via `terraform`. That is a valid point, but isn't something the tool currently support. In order to make that happen, there needs non-trivial effort for every currently supported resource (see what [`terraformer`](https://github.com/GoogleCloudPlatform/terraformer/tree/master/providers/azure) does). It is hardly to be able to keep up with the provider as the effort is almost as much as you implementing the provider itself. That's why we didn't choose that way. Instead, we hope to provide a way for users to transfer to using `terraform` in a smooth way, and provide them with a baseline to work on. Users are free to make modifications on the generated cfg, e.g. using implicit dependencies across resources instead of the exlicit ones, adding the missing `O+C` properties (though not necessary).

Back to your case, the `private_ip_address` is still a `O+C` property from the POV of schema, even if it is required when it is a static one. If the resource is imported, since it is a `O+C` property, it means when it is a static one, the provider is able to get its value as it is set in the remote and is exported. So if the provider later add validation logic to verify that in case of static, the `private_ip_address` has to be set, then in this case the generated cfg and state will still work out of the box, i.e. you don't need to modify the output of `aztfy`. The only moment that you need to manually add it up is when you want to reproduce the provision using the generated cfg, since it is a new creation (i.e. there is no state yet) you will have to add the `private_ip_address` to pass the validation for either the provider and the API.
