### ISSUE TITLE
Support data disks

### ISSUE THREAD

**Issue by Klaas-** [Azure/aztfy#34]
Hi,
currently it does not seem to be able to recognize azurerm_managed_disk and azurerm_virtual_machine_data_disk_attachment resources in azure

Greetings
Klaas

**Comment by magodo** [comment]
@Klaas- Thank you for submitting this!

For the `azurerm_managed_disk` *is not supported*, I assume you mean you didn't see it is auto filled in the resource list. This is because the tool didn't recognize this API path as a `azurerm_managed_disk` (for this specific case, it is fixed in #35). In this case, you can manually identify the resource type and fill in with `azurerm_managed_disk`.

For the `azurerm_virtual_machine_data_disk_attachment`, due to it is an *association*/*attachment* resource, currently it is not well supported by the tool (see the [limitation](https://github.com/Azure/aztfy#limitation)). Please follow issue #3 for any progress.

**Comment by Klaas-** [comment]
I did not see the managed disks at all in the resource selection, maybe I need to compile from dev branch? I was using version 0.0.6

About the attachment: there is a 1/1 resource association for normal managed disks, it's not like a shared disk that gets attached to multiple resources. That's why I assumed the limitation does not apply here :)

**Comment by magodo** [comment]
@Klaas- Yes, you'll need to install the latest one. Just run: `go install github.com/Azure/aztfy@latest`.

For the association, I mean from the API model, there is actually no such resource called `azurerm_virtual_machine_data_disk_attachment` in Azure, it is actually modeled as a property in the VM's model. The abstraction is introduced by terraform only, usally for better user experience. So no matter the disk is associated with one or multiple VMs, as long as it is some abstraction of terraform, I'll call them association resource. To support these kinds of resources need additional effort, especially need to follow up when the provider evolves. Due to the workload needed, currently we are still on hold to add the support for it.
