### ISSUE TITLE
All env variables are set but still getting an error

### ISSUE THREAD

**Issue by letmetechyou** [Azure/aztfy#358]
Getting this error after running aztfy rg.  I'm logged in and authenticated via the cli as well.  are there any gotchas when it comes to using service accounts or user accounts. 
![image](https://user-images.githubusercontent.com/51865837/218854604-977512f8-ad3b-4556-b67f-ba3c7397eb88.png)

**Comment by magodo** [comment]
@letmetechyou If you have specified the client id, I think the underlying auth method being chosen is to using the client id + client secret, since you didn't specify the client secret, you got this error.

Normally, if you loggined in via azure cli, you don't need to specify any environment variable at all.

**Comment by magodo** [comment]
What version of Azure CLI you are using? The error above is from the provider: https://github.com/hashicorp/terraform-provider-azurerm/blob/878c611a0df60424ad07ccbf85999099a4e8996a/vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_token.go#L243-L250

My proposal is either you use client secret auth method per: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret. Or updating the Azure CLI to latest version.

**Comment by letmetechyou** [comment]
version 2.45.0 and im using client auth secret method. ill continue to troubleshoot as much as i can.

**Comment by letmetechyou** [comment]
ahhhhhh disregard. typo in my client secret variable.
