### ISSUE TITLE
Persistent "resource group does not exist" error

### ISSUE THREAD

**Issue by gysiedebruyn** [Azure/aztfy#61]
Using the latest version 0.1.1:

```
aztfy -v
0.1.1(5654025)
```

I keep on running into an error suggesting the resource group does not exist. I did double check that:
- I am logged into az cli ✅ 
- The subscription containing the resource group is set and default ✅ 
- the resource group exists ✅ 

But I keep on getting the error that the resource group does not exist:

```
Azure Terrafy 
  
  exporting arm template of resource group jdb-test-rg: resources.GroupsClient#ExportTemplate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceGroupNotFound" Message="Resource
  group 'jdb-test-rg' could not be found." 
```

I am running this from the Terraform supplied docker image:

```
ARG   TERRAFORM_VERSION=1.1.7
FROM  hashicorp/terraform:${TERRAFORM_VERSION}
ARG   AZTFY_VERSION=0.1.1
...
...
...
# add the aztfy binary
RUN curl -L https://github.com/Azure/aztfy/releases/download/v${AZTFY_VERSION}/aztfy_v${AZTFY_VERSION}_linux_amd64.zip -o /tmp/aztfy.zip && \
    unzip /tmp/aztfy.zip -d /usr/local/bin && \
    chmod +x /usr/local/bin/aztfy
```

This is the underlying OS of the Terrform image:

```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Any ideas why it keeps on telling me the resource group does not exist?

**Comment by magodo** [comment]
@gysiedebruyn Thank you for submitting this! Assuming you have correctly login via az cli **within** the container, the problem might be due to the current active/default subscription in az cli is not the one contains the specified resource group. Two ways to fix this, one is to change the default sub via `az account set -s <sub id>`; another is to specify the subscription id that `aztfy` is expected to use via [`subscription_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#subscription_id).

**Comment by gysiedebruyn** [comment]
Found my problem, everything was correct except the underlying `ARM_SUBSCRIPTION_ID`. Changing that fixed it
