### ISSUE TITLE
aztfty unable to export resource  group more that 200 templates

### ISSUE THREAD

**Issue by manjeetsinghcodz** [Azure/aztfy#76]
Hello, 

 i have following error when doing an import : 

>>>
aztfy XXXX
  exporting arm template of resource group XXXXX: resources.GroupsClient#ExportTemplate: Failure sending request: StatusCode=0 -- Original   
  Error: autorest/azure: Service returned an error. Status=<nil> Code="ExportTemplateResourcesLimitExceeded" Message="Export template is not supported
  for resource groups that have more than '200' resources."
<<<

Please help. Thank you

**Comment by magodo** [comment]
@manjeetsinghcodz Thank you for submitting this!

This is because currently `aztfy` is using the ARM template to do the resource listing and dependency resolvation. As seen from the error message, [ARM template export has limitation of up to 200 resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/export-template-portal#limitations). We are planning to strip the dependency on ARM template, but need efforts to make it happen.

**Comment by manjeetsinghcodz** [comment]
@magodo  thanks for this info. but is there a way to import only one resource from a resource-group with aztfy ?

**Comment by magodo** [comment]
@manjeetsinghcodz You can do that via https://github.com/magodo/tfadd, which is used by `aztfy` under the hood.

**Comment by rtorato** [comment]
> @manjeetsinghcodz You can do that via https://github.com/magodo/tfadd, which is used by `aztfy` under the hood.

Hi @magodo , but for this...i do need to create the tf file first and it'll like an import? Or not? I didn't understand well how to use the tfadd to import, like, a VM or an app gateway

**Comment by magodo** [comment]
@rtorato You can check out the readme: https://github.com/magodo/tfadd#usage. Once https://github.com/Azure/aztfy/pull/166 is merged, there would be first class subcommand for the single resource scenario.

**Comment by magodo** [comment]
@rtorato v0.6.0 is now released.
