### ISSUE TITLE
Unable to import App Services

### ISSUE THREAD

**Issue by PhilBroderick** [Azure/aztfy#92]
aztfy v0.3.0
terraform v1.1.9

I have a resource group with an App Service Plan and 3 App Services, as well as some other resources. The App Services are recognized on the initial import:

![app-service-not-imported](https://user-images.githubusercontent.com/33251762/168431126-6769b8c2-d1eb-4bee-b54b-460918c5825a.png)

and pressing `r` will even provide some suggested resource types. However then generated `.aztfyResourceMapping.json` doesn't include the resources.

Is there any further information that may point to the issue?

**Comment by magodo** [comment]
@PhilBroderick Currently, the generated resource mapping file only includes import items that are filled with a TF resource address, otherwise, the item is regarded as skipped and won't be included in the mapping file. Pressing `r` shows possible TF resource types, whilst users are still needed to decide which one to import. Hope this clarifies.

**Comment by PhilBroderick** [comment]
@magodo sorry yes with you now!
